jd:
  flag: false
mt:
  flag: false
mybatis:
  mapperLocations: classpath*:/mybatis/mapper/*.xml
  configLocation: classpath:/mybatis/mybatis-config.xml

defaultsql:
  datasource:
    url: jdbc:mysql://rm-2ze8a4ahn220ckja1wo.mysql.rds.aliyuncs.com:3306/water_supplier?useSSL=false&allowMultiQueries=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: Wql719473
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: wall,stat,slf4j
    connectionInitSqls: ["set names utf8mb4;"]
  slave1:
    datasource:
      url: jdbc:mysql://rm-2ze8a4ahn220ckja1wo.mysql.rds.aliyuncs.com:3306/water_supplier?useSSL=false&allowMultiQueries=true&characterEncoding=utf8&characterSetResults=utf8
      username: root
      password: Wql719473
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 5
      maxActive: 50
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: wall,stat,slf4j
      connectionInitSqls: ["set names utf8mb4;"]

spring:
  devtools:
    restart:
      enabled: false
  application:
    name: bservice
server:
  port: 8080
  servlet:
    context-path: /bservice

